-- AUTOR HECTOR HUGO HIDALGO MARTINEZ
-- CREATE DATABASE PAPELERIA;

-- USE PAPELERIA;

CREATE TABLE ADDRESS ( 
	ID_ADDRESS	integer(11)  NOT NULL AUTO_INCREMENT,
	ADDRESS   	varchar(200) NOT NULL NULL,
	NUMBERINT 	integer(11) NOT NULL NULL,
	POSTALCODE	varchar(25) NOT NULL NULL,
	COMMENTS  	varchar(100) NULL,
	PRIMARY KEY(ID_ADDRESS)
);


CREATE TABLE CUSTOMER( 
	CUSTOMER_ID	integer(11) NOT NULL AUTO_INCREMENT,
	NAME       	varchar(50) NOT NULL,
	LASTNAME   	varchar(25) NOT NULL,
	PHONE      	varchar(25) NULL,
	ID_ADDRESS 	integer(11) NOT NULL,
	PRIMARY KEY(CUSTOMER_ID)
);

ALTER TABLE CUSTOMER
	ADD CONSTRAINT ADDRESS_FK
	FOREIGN KEY(ID_ADDRESS)
	REFERENCES ADDRESS(ID_ADDRESS);



CREATE TABLE MARK ( 
	MARK_ID  	integer(11) NOT NULL AUTO_INCREMENT,
	MARK_NAME	varchar(25) NOT NULL,
	PRIMARY KEY(MARK_ID)
);



CREATE TABLE PRODUCT( 
    PRODUCT_ID 	int(11) NOT NULL AUTO_INCREMENT,
    PRODUCTNAME	varchar(100) NOT NULL,
    PRICE      	double NOT NULL,
    TAXLESS    	varchar(25) NULL,
    MARK_ID    	int(11) NOT NULL,
    PRIMARY KEY(PRODUCT_ID)
);

ALTER TABLE PRODUCT
    ADD CONSTRAINT MARK_FK
	FOREIGN KEY(MARK_ID)
	REFERENCES mark(MARK_ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT;

CREATE TABLE ORDERITEM ( 
	ORDER_ID   	integer(11)  NOT NULL AUTO_INCREMENT,
	TOTAL      	double NOT NULL,
	DATEORDER  	date NOT NULL,
	CUSTOMER_ID	integer(11) NOT NULL,
	PRIMARY KEY(ORDER_ID)
);

ALTER TABLE ORDERITEM 
	ADD CONSTRAINT customer_fk
	FOREIGN KEY(CUSTOMER_ID)
	REFERENCES customer(CUSTOMER_ID);

CREATE TABLE ORDERDETAIL ( 
	ORDER_ID      	integer(11) NOT NULL,
	PRODUCT_ID    	integer(11) NOT NULL,
	NUMBERPRODUCTS	integer(11) NOT NULL,
	SUBTOTAL      	double NOT NULL,
	PRIMARY KEY(ORDER_ID,PRODUCT_ID)
);

ALTER TABLE ORDERDETAIL
	ADD CONSTRAINT PRODUCT_FK
	FOREIGN KEY(PRODUCT_ID)
	REFERENCES product(PRODUCT_ID);

ALTER TABLE ORDERDETAIL
	ADD CONSTRAINT ORDER_FK
	FOREIGN KEY(ORDER_ID)
	REFERENCES orderitem(ORDER_ID);
